# Use the official Node.js image as base
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend files to the working directory
COPY . .

# Expose the port your app runs on
EXPOSE 3005

# Define the command to run your app
CMD ["node" "server.js"]